server:
  port: 8090

spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"

  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # change to 'validate' in production if schema already exists
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
