spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///D://Microservices//config"
        #search-locations: "file:///D://Microservices//config"
        #search-locations: "classpath:/config"
server:
  port: 8071


