spring:
  application:
    name: configserver
  profiles:
    active: git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aditya0608/BankRepository.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
        # Uncomment below for native profile
        # native:
        #   search-locations: file:///D://Microservices//config
        # search-locations: classpath:/config

server:
  port: 8071

encrypt:
  key: 6764RJKVNF3289233RJVM

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
